###
# Reset database
PUT {{host}}/debug/reset
Authorization: Bearer {{$processEnv %token}}

###
# Initialize database with demo data
PUT {{host}}/debug/init
Authorization: Bearer {{$processEnv %token}}

{
	"room": "test",
	"players": ["Vlad", "George", "John"],
	"wordlists": ["test-list", "card-poison", "card-dagger", "team-galactic", "team-green", "countries", "technology", "pokemon"]
}

###
# Initialize room and players
# @prompt room Name of the room.
# @prompt players Name of players, comma-separated and double-quoted.
PUT {{host}}/debug/init
Authorization: Bearer {{$processEnv %token}}

{
	"room": "{{room}}",
	"players": [{{players}}],
}

###
# Add wordlists
# @prompt wordlists Name of wordlists, as comma-separated double-quoted strings.
# Possible wordlists: "test-list", "card-poison", "card-dagger", "team-galactic", "team-green", "countries", "technology", "pokemon"
PUT {{host}}/debug/init
Authorization: Bearer {{$processEnv %token}}

{
	"wordLists": [{{wordlists}}]
}
