###
# Reset room
# @prompt room Name of room
POST {{host}}/room/{{room}}/reset
Authorization: Bearer {{$processEnv %token}}

###
# Start room
# @prompt room Name of room
POST {{host}}/room/{{room}}/start
Authorization: Bearer {{$processEnv %token}}

###
# Randomly assign GM to one player
# @prompt room Name of room
POST {{host}}/room/{{room}}/gm
Authorization: Bearer {{$processEnv %token}}

###
# Assign specific player as GM
# @prompt room Name of room
# @prompt name Name of player
POST {{host}}/room/{{room}}/gm/{{name}}
Authorization: Bearer {{$processEnv %token}}
