###
# List rooms
GET {{host}}/room/

###
# Get room
# @prompt room Name of room
GET {{host}}/room/{{room}}

###
# Add room
# @prompt room Name of room
PUT {{host}}/room/{{room}}
Authorization: Bearer {{$processEnv %token}}

{
	"usesWords": true
}

###
# Update room status
# @prompt room Name of room
# @prompt status Room status, one of "not-ready", "started", or "completed"
PATCH {{host}}/room/{{room}}
Authorization: Bearer {{$processEnv %token}}

{
	"status": {{status}}
}

###
# Update whether the room uses words
# @prompt room Name of room
# @prompt usesWords Whether the room uses words, true or false
PATCH {{host}}/room/{{room}}
Authorization: Bearer {{$processEnv %token}}

{
	"usesWords": {{usesWords}}
}

###
# Update room's wordlists
# @prompt room Name of room
# @prompt wordLists Wordlists, as comma-separated double-quoted strings
PATCH {{host}}/room/{{room}}
Authorization: Bearer {{$processEnv %token}}

{
	"wordLists": [{{wordLists}}]
}

###
# Update room's numWords
# @prompt room Name of room
# @prompt numWords Number of words to distribute on game start
PATCH {{host}}/room/{{room}}
Authorization: Bearer {{$processEnv %token}}

{
	"numWords": {{numWords}}
}

###
# Delete room
# @prompt room Name of room
DELETE {{host}}/room/{{room}}
Authorization: Bearer {{$processEnv %token}}
