###
# Add words to wordlist
# @prompt wordlist Name of wordlist
# @prompt words Words, as comma-separated double-quoted strings
PUT {{host}}/wordlist/{{wordlist}}/words
Authorization: Bearer {{$processEnv %token}}

{
	"words": [{{words}}]
}

###
# Delete words from wordlist
# @prompt wordlist Name of wordlist
# @prompt words Words, as comma-separated double-quoted strings
DELETE {{host}}/wordlist/{{wordlist}}/words
Authorization: Bearer {{$processEnv %token}}

{
	"words": [{{words}}]
}
