@name = test-list

###
# Add words to wordlist
# @prompt words Comma-separated double-quoted words.
PUT {{host}}/api/wordlist/{{name}}/words
Authorization: Bearer {{$dotenv %token}}

{
	"words": [{{words}}]
}

###
# Delete words from wordlist
# @prompt words Comma-separated double-quoted words.
DELETE {{host}}/api/wordlist/{{name}}/words
Authorization: Bearer {{$dotenv %token}}

{
	"words": [{{words}}]
}
