###
# List wordlists
GET {{host}}/api/wordlist

###
# Get wordlist
# @prompt wordlist Name of wordlist
GET {{host}}/api/wordlist/{{wordlist}}

###
# Add wordlist
# @prompt wordlist Name of wordlist
# @prompt description The description of this wordlist
# @prompt icon Icon to use for this wordlist
PUT {{host}}/api/wordlist/{{wordlist}}
Authorization: Bearer {{$processEnv %token}}

{
	"description": "{{description}}",
	"icon": "{{icon}}"
}

###
# Update wordlist description
# @prompt wordlist Name of wordlist
# @prompt description The description of this wordlist
PATCH {{host}}/api/wordlist/{{wordlist}}
Authorization: Bearer {{$processEnv %token}}

{
	"description": "{{description}}"
}

###
# Update wordlist icon
# @prompt wordlist Name of wordlist
# @prompt icon Icon to use for this wordlist
PATCH {{host}}/api/wordlist/{{wordlist}}
Authorization: Bearer {{$processEnv %token}}

{
	"icon": "{{icon}}"
}

###
# Delete wordlist
# @prompt wordlist Name of wordlist
DELETE {{host}}/api/wordlist/{{wordlist}}
Authorization: Bearer {{$processEnv %token}}
