name = "assassin"
main = "src/index.ts"
compatibility_date = "2023-06-17"
usage_model = "bundled"
env = { }
route = { pattern = "assassin.vlad.gg", custom_domain = true }

kv_namespaces = [
    { binding = "OPENID", id = "ced561d5ee6b4cd9a10ce389886fc84e", preview_id = "ced561d5ee6b4cd9a10ce389886fc84e" }
]

[site]
bucket = "./dist"

[triggers]
crons = [ ]

[[d1_databases]]
binding = "D1DATABASE"
database_name = "assassin"
database_id = "a24a1078-cacd-42dd-82d2-c8865fd4c306"
