name = "assassin"
main = "src/index.ts"
compatibility_date = "2023-07-05"
usage_model = "bundled"
site = { bucket = "./dist" }
triggers = { crons = [] }

route = { pattern = "assassin.vlad.gg", custom_domain = true }
vars = { ENVIRONMENT = "live", BASE_URL="https://assassin.vlad.gg" }
kv_namespaces = [
    { binding = "OPENID", id = "ced561d5ee6b4cd9a10ce389886fc84e", preview_id = "ced561d5ee6b4cd9a10ce389886fc84e" },
    { binding = "CONFIG", id = "b3e6b454e3854672a07c1c4522468cb2", preview_id = "b3e6b454e3854672a07c1c4522468cb2" }
]
d1_databases = [
    { binding = "D1DATABASE", database_name = "assassin", database_id = "a24a1078-cacd-42dd-82d2-c8865fd4c306" },
]

[env.dev]
route = { pattern = "dev.assassin.vlad.gg", custom_domain = true }
vars = { ENVIRONMENT = "dev", BASE_URL="https://dev.assassin.vlad.gg" }
kv_namespaces = [
    { binding = "OPENID", id = "ced561d5ee6b4cd9a10ce389886fc84e", preview_id = "ced561d5ee6b4cd9a10ce389886fc84e" },
    { binding = "CONFIG", id = "8d40e4cf1eaa40ccaa6810bb9b8197e8", preview_id = "8d40e4cf1eaa40ccaa6810bb9b8197e8" }
]
d1_databases = [
    { binding = "D1DATABASE", database_name = "assassin-dev", database_id = "dfc20066-c513-41b9-a72c-0d23eedf9624" },
]

[env.staging]
route = { pattern = "staging.assassin.vlad.gg", custom_domain = true }
vars = { ENVIRONMENT = "staging", BASE_URL="https://staging.assassin.vlad.gg" }
kv_namespaces = [
    { binding = "OPENID", id = "ced561d5ee6b4cd9a10ce389886fc84e", preview_id = "ced561d5ee6b4cd9a10ce389886fc84e" },
    { binding = "CONFIG", id = "1f0a79f421ac46c58e9961a0f89f2282", preview_id = "1f0a79f421ac46c58e9961a0f89f2282" }
]
d1_databases = [
    { binding = "D1DATABASE", database_name = "assassin-staging", database_id = "3294dcd9-1d30-453e-b2d0-fbe6e15683dd" },
]

[env.live]
route = { pattern = "assassin.vlad.gg", custom_domain = true }
vars = { ENVIRONMENT = "live", BASE_URL="https://assassin.vlad.gg" }
kv_namespaces = [
    { binding = "OPENID", id = "ced561d5ee6b4cd9a10ce389886fc84e", preview_id = "ced561d5ee6b4cd9a10ce389886fc84e" },
    { binding = "CONFIG", id = "b3e6b454e3854672a07c1c4522468cb2", preview_id = "b3e6b454e3854672a07c1c4522468cb2" }
]
d1_databases = [
    { binding = "D1DATABASE", database_name = "assassin", database_id = "a24a1078-cacd-42dd-82d2-c8865fd4c306" },
]
