name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/shared-build.yml
    secrets: inherit

  deploy-staging:
    needs: ['build']
    uses: ./.github/workflows/shared-deploy.yml
    with:
      environment: staging
      baseUrl: https://staging.assassin.vlad.gg
    if: github.event_name == 'pull_request'
    secrets: inherit

  deploy-live:
    needs: ['build']
    uses: ./.github/workflows/shared-deploy.yml
    with:
      environment: live
      baseUrl: https://assassin.vlad.gg
    if: github.event_name != 'pull_request'
    secrets: inherit
