name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/shared-build.yml
    secrets: inherit

  push-kv:
    needs: ['build']
    uses: ./.github/workflows/shared-kv.yml
    with:
      environment: live
    secrets: inherit

  deploy:
    needs: ['build']
    uses: ./.github/workflows/shared-deploy.yml
    with:
      environment: live
      baseUrl: https://assassin.vlad.gg
    secrets: inherit
