name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: v18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
