name: nx-cloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build affected files
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    with:
      main-branch-name: main
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=format --parallel=3
        npx nx affected --target=build --parallel=3
  deploy:
    name: Deploy new build
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Initialize Nx Cloud
        run: npx nx-cloud start-ci-run
      - name: Pull CF secret from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.zhr.one
          role: dns
          path: github
          method: jwt
          jwtGithubAudience: sigstore
          secrets: |
            /ci-cd/assassin/cloudflare CLOUDFLARE_API_TOKEN
      - name: Deploy with Wrangler
        run: npm run deploy

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    with:
      number-of-agents: 3
